### GET Books
GET http://localhost:4004/odata/v4/bookshop/Books

### GET LowStock
GET http://localhost:4004/odata/v4/bookshop/LowStock

### GET Books
GET http://localhost:4004/odata/v4/bookstock/BooksLowStock

### GET totalStock
GET http://localhost:4004/odata/v4/bookshop/totalStock()

### GET Books
GET http://localhost:4004/odata/v4/bookshop/Books(8534bc44-644c-8fa4-195f-0fe8b0c39bda)/stockValue()  
